language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
before_install:
  - npm install coveralls -g
  - npm install mocha-lcov-reporter -g
script: npm run-script coveralls
branches:
  only:
    - master
    - development
